### ISSUE TITLE
"Show More" button disappeared from record list

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#7]
For example, in the offers section in the following pages there should be a show more button. It used to be there before the merge:

`http://localhost:5009/phone.html?value=http://dig.isi.edu/ht/data/phone/(phone_redacted)&field=_id&blur=true`

`http://localhost:5009/seller.html?value=http://dig.isi.edu/ht/data/seller/cluster/4BD795974EF4A77D13F3F21B139F64A09CC01138&field=_id&blur=true`

**Comment by ThomasSchellenbergNextCentury** [comment]
So, before the merge the records-list would show a scrollbar if there were more than a few records, and the "Show More" button would appear once you scrolled to the bottom.  Since these offer sections show all 25 offers without a scrollbar, the "scroll-to-the-bottom" events don't occur to cause the "Show More" buttons to appear.

I know you removed the height restriction from the records-list in order to view more than a handful records at a time.  How many visible records at a time are important to you?  20?  25?  More?  This will affect my implementation of a solution.  Thanks.

**Comment by ThomasSchellenbergNextCentury** [comment]
I have pushed a temporary fix to master that should be sufficient for the present (possibly sufficient for the release).  I'll look into longer term solutions over the next few days to find one that works for all of us.

**Comment by szeke** [comment]
Did you add a show more button?

**Comment by szeke** [comment]
Looks good
